[project]
name = "custom-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-groq>=1.1.2",
    "mcp-use>=1.6.0",
    "mcp[cli]>=1.26.0",
    "nest-asyncio>=1.6.0",
    "python-dotenv>=1.2.1",
]
